app:
  service-principal: HTTP/service.com
  #keytab-location: .\\spring-security-sso\\spring-security-sso-kerberos\\krb-test-workdir\\example.keytab
  #keytab-location: d:\\kerberos\\service.keytab
  keytab-location: .\\kerberos-config\\service.keytab
  #location: .\\kerberos-config\\service.keytab

server:
  port: 8081
  servlet:
    context-path: /server
spring:
  thymeleaf:
    prefix: classpath:/templates/
  security:
    user:
      name: server
      password: 1234
      roles: vip