app:
  keytab-location: Kerberos-config/client.keytab
  access-url: http://localhost:8081/server/hello
  service-principal: server/admin
  user-principal: client/admin
server:
  port: 8082
  servlet:
    context-path: /client
spring:
  security:
    user:
      name: client/admin
      password: 1234
      roles: role